// GENERATED by tools/release_artifacts.ts — do not edit by hand.
// Release-asset names + sha256 digests for the native addon; the loader
// downloads these from the GitHub release for version 0.4.0 and refuses
// anything that does not match. Regenerate: deno task release:artifacts

export const RELEASE_ARTIFACTS = {
  "version": "0.4.0",
  "assets": {
    "darwin-aarch64": {
      "file": "libnumber0_iroh-aarch64-apple-darwin.dylib",
      "sha256": "5c63bde32c5319312285509736d99f0c57b00111bd5936812a552268fe2188eb",
    },
    "linux-x86_64": {
      "file": "libnumber0_iroh-x86_64-unknown-linux-gnu.so",
      "sha256": "1244634b48aba29ccce992be7d7ba69e3d4bb6f33d07368811fe604969c6a08d",
    },
    "linux-aarch64": {
      "file": "libnumber0_iroh-aarch64-unknown-linux-gnu.so",
      "sha256": "00ebb991e4310eef7a379bc9676da496f78b96d815832187ef043ccf5f62366e",
    },
  },
} as const;
