// Regenerates src/native/artifacts.ts from native/iroh-js/prebuilt/ and
// deno.json: the release-asset names and sha256 digests the JSR-published
// loader will accept when downloading the native addon from the GitHub
// release. CI verifies the file is fresh (`git diff --exit-code`).
//
// Run: deno task release:artifacts

const TRIPLES: Record<string, { dir: string; ext: string }> = {
  "darwin-aarch64": { dir: "aarch64-apple-darwin", ext: "dylib" },
  "linux-x86_64": { dir: "x86_64-unknown-linux-gnu", ext: "so" },
  "linux-aarch64": { dir: "aarch64-unknown-linux-gnu", ext: "so" },
};

const version = JSON.parse(await Deno.readTextFile("deno.json")).version as string;

const assets: Record<string, { file: string; sha256: string }> = {};
for (const [platform, { dir, ext }] of Object.entries(TRIPLES)) {
  const source = `native/iroh-js/prebuilt/${dir}/libnumber0_iroh.${ext}`;
  const bytes = await Deno.readFile(source);
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  const sha256 = [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join("");
  assets[platform] = { file: `libnumber0_iroh-${dir}.${ext}`, sha256 };
}

const banner = `// GENERATED by tools/release_artifacts.ts — do not edit by hand.
// Release-asset names + sha256 digests for the native addon; the loader
// downloads these from the GitHub release for version ${version} and refuses
// anything that does not match. Regenerate: deno task release:artifacts

export const RELEASE_ARTIFACTS = ${JSON.stringify({ version, assets }, null, 2)} as const;
`;
await Deno.writeTextFile("src/native/artifacts.ts", banner);
console.log(`src/native/artifacts.ts regenerated for v${version}`);
for (const [platform, asset] of Object.entries(assets)) {
  console.log(`  ${platform}: ${asset.file} ${asset.sha256.slice(0, 16)}…`);
}
